# Generated by Django 3.0.5 on 2020-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image_url', models.URLField(max_length=500)),
                ('blog_url', models.URLField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
